title: Dien Phan
author: Dien Phan
email: tdien105@gmail.com
description: >
  My journey to become a DBRE
show_excerpts: true

sass:
  sass_dir: _sass
plainwhite:
  name: Dien Phan
  tagline: SRE, DBRE
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  portfolio_image: "assets/portfolio.png"
  html_lang: "en"
  condensed_mobile:
    #- home
    - page
    - post
  social_links:
    github: tdien105
  navigation:
    - title: About
      url: "/about"

# Build settings
#theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
